themetal_markers_text_e5fa3adf = "Intro"
themetal_markers_text_c5cccaf7 = "Strofa 1"
themetal_markers_text_1c1a2ba4 = "Bridge 1"
themetal_markers_text_3abdeb66 = "Ritornello/Bridge"
themetal_markers_text_5cc59b4d = "Strofa 2"
themetal_markers_text_a26b5fdb = "Breakdown infernale"
themetal_markers_text_eda21fe1 = "Finale"
