themetal_markers_text_e5fa3adf = "Intro"
themetal_markers_text_c5cccaf7 = "Strophe 1"
themetal_markers_text_1c1a2ba4 = "Bridge 1"
themetal_markers_text_3abdeb66 = "Refrain / Middle 8"
themetal_markers_text_5cc59b4d = "Strophe 2"
themetal_markers_text_a26b5fdb = "Höllischer Zusammenbruch"
themetal_markers_text_eda21fe1 = "Outro"
